# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Nico/Documents/GitHubActivities/PlantsVsZombies/withNico/withNico.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
# IP: The module: 'blk_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nico/Documents/GitHubActivities/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Nico/Documents/GitHubActivities/PlantsVsZombies/withNico/withNico.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
# IP: The module: 'blk_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nico/Documents/GitHubActivities/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
