set_property SRC_FILE_INFO {cfile:c:/Users/camer/Documents/GitHub/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../withNico.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:myClock} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/camer/Documents/GitHub/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1/blk_mem_gen_1_in_context.xdc rfile:../../../../../withNico.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1/blk_mem_gen_1_in_context.xdc id:2 order:EARLY scoped_inst:grid/grassRomBlock} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/camer/Documents/GitHub/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc rfile:../../../../../withNico.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:3 order:EARLY scoped_inst:grid/peaShooterMaskRomBlock} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/camer/Documents/GitHub/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2/blk_mem_gen_2_in_context.xdc rfile:../../../../../withNico.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2/blk_mem_gen_2_in_context.xdc id:4 order:EARLY scoped_inst:grid/peaShooterRomBlock} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/camer/Documents/GitHub/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4/blk_mem_gen_4_in_context.xdc rfile:../../../../../withNico.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4/blk_mem_gen_4_in_context.xdc id:5 order:EARLY scoped_inst:grid/sunflowerMaskRomBlock} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/camer/Documents/GitHub/PlantsVsZombies/withNico/withNico.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3/blk_mem_gen_3_in_context.xdc rfile:../../../../../withNico.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3/blk_mem_gen_3_in_context.xdc id:6 order:EARLY scoped_inst:grid/sunflowerRomBlock} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/camer/Stuff/University/DSD/assignment/assignment.srcs/constrs_1/new/constraints.xdc rfile:../../../../../../../../../Stuff/University/DSD/assignment/assignment.srcs/constrs_1/new/constraints.xdc id:7} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name myClock/clk_out1 -source [get_pins myClock/clk_in1] -edges {1 2 3} -edge_shift {0.000 -0.304 -0.608} [get_pins myClock/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells myClock]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins grid/grassRomBlock/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells grid/grassRomBlock]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins grid/peaShooterMaskRomBlock/clka]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells grid/peaShooterMaskRomBlock]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins grid/peaShooterRomBlock/clka]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells grid/peaShooterRomBlock]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins grid/sunflowerMaskRomBlock/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells grid/sunflowerMaskRomBlock]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins grid/sunflowerRomBlock/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells grid/sunflowerRomBlock]
set_property src_info {type:XDC file:7 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells myClock]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells grid/grassRomBlock]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells grid/peaShooterMaskRomBlock]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells grid/peaShooterRomBlock]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells grid/sunflowerMaskRomBlock]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells grid/sunflowerRomBlock]
